### ISSUE TITLE
Demo Presentation

### ISSUE THREAD

**Issue by johnnyboysydney** [johnnyboysydney/The-Future#11]
Preparing the Presentation for Saturday demo, 
-Create the slides, 
-Create the pitch
-Create the sale

**Comment by blin124** [comment]
[Presentation_description & user story.pptx](https://github.com/johnnyboysydney/The-Future/files/4430410/Presentation_description.user.story.pptx)
Full ppt

**Comment by johnnyboysydney** [comment]
We have done a test demo between us and we are ready for demonstration. 
Haden will go first then Cynthia and last me, 

We have started the presentation first and therefore finalised the project. 
Closing.
